
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install metadata validator
        run: wget https://github.com/loot/metadata-validator/releases/download/0.18.0/metadata-validator-0.18.0-0-g143cb72_0.18.0-Linux.tar.xz -O - | tar -xJ --strip-components=1

      - name: Install parser
        run: npm install -g js-yaml

      - name: Download prelude file
        run: wget https://raw.githubusercontent.com/loot/prelude/v0.18/prelude.yaml

      - name: Run metadata validator
        run: |
          ./metadata_validator $GITHUB_WORKSPACE/masterlist.yaml
          ./metadata_validator $GITHUB_WORKSPACE/masterlist.yaml $GITHUB_WORKSPACE/prelude.yaml
          js-yaml $GITHUB_WORKSPACE/masterlist.yaml > /dev/null
